name: gnome-taquin
version: 3.22.0
summary: Slide tiles to their correct places
description: |
  Taquin is a computer version of the 15-puzzle and other sliding puzzles.

  The object of Taquin is to move tiles so that they reach their places,
  either indicated with numbers, or with parts of a great image.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-taquin:
    interface: dbus
    bus: session
    name: org.gnome.taquin

apps:
  gnome-taquin:
    command: desktop-launch gnome-taquin
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - pulseaudio
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.taquin.desktop
    environment:
      PATH: $SNAP/usr/games:$PATH

parts:
  gnome-taquin:
    build-attributes: [no-system-libraries]
    after: [desktop-gnome-platform]
    source: https://git.gnome.org/browse/gnome-taquin
    source-type: git
    source-tag: 3.22.0
    prepare:
      sed -i.bak -e 's|=gnome-taquin$|=${SNAP}/meta/gui/gnome-taquin.png|g' data/org.gnome.taquin.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/gnome-taquin.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.taquin.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/snap/gnome-taquin/current/usr, --bindir=/snap/gnome-taquin/current/usr/games]
    organize:
      snap/gnome-taquin/current/usr: usr
    build-packages:
     - appstream-util
     - gnome-pkg-tools
     - pkg-config
     - intltool
     - libglib2.0-dev
     - libgtk-3-dev
     - librsvg2-dev
     - libcanberra-gtk3-dev
     - valac
     - yelp-tools

